"""Per-tool tracks, the toolUnique discordance track, and hub assembly.

Follows the UCSC contributed-tracks layout: one directory per assembly named by
NCBI accession, IDENTICAL data filenames in every assembly directory (so a
single trackDb.txt serves all of them), binary formats only, and an HTML
documentation page per track.

Because the filenames must match across assemblies, a tool that did not run
still gets an empty bigBed rather than a missing file -- otherwise trackDb would
have to vary per assembly, which the layout forbids.
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

PERTOOL_AS = """table repeatByTool
"Repeat annotation from a single tool"
    (
    string  chrom;          "Reference sequence chromosome or scaffold"
    uint    chromStart;     "Start position in chromosome"
    uint    chromEnd;       "End position in chromosome"
    string  name;           "Repeat family name as reported by the tool"
    uint    score;          "Alignment score, capped at 1000"
    char[1] strand;         "+ or - or . for unknown"
    uint    thickStart;     "Start of thick drawing"
    uint    thickEnd;       "End of thick drawing"
    uint    reserved;       "RGB colour by canonical class"
    string  rawClass;       "Class/family label exactly as the tool reported it"
    string  canonicalClass; "Harmonised classification path"
    string  divergence;     "Divergence from family consensus (%)"
    string  deletion;       "Deletion relative to consensus (%)"
    string  insertion;      "Insertion relative to consensus (%)"
    string  consensusRange; "Matched interval within the family consensus"
    string  evidence;       "Structural or homology-based call"
    string  overlapStatus;  "Relationship to other hits from the same tool"
    string  hitId;          "Tool's own identifier for this hit"
    )
"""

UNIQUE_AS = """table toolUnique
"Genomic intervals called by exactly one tool"
    (
    string  chrom;          "Reference sequence chromosome or scaffold"
    uint    chromStart;     "Start position in chromosome"
    uint    chromEnd;       "End position in chromosome"
    string  name;           "Tool and class"
    uint    score;          "1000 (fixed)"
    char[1] strand;         "+ or - or . for unknown"
    uint    thickStart;     "Start of thick drawing"
    uint    thickEnd;       "End of thick drawing"
    uint    reserved;       "RGB colour of the calling tool"
    string  tool;           "The only tool calling a repeat here"
    string  canonicalClass; "Its classification"
    string  otherEligible;  "Tools able to call this class that did NOT"
    string  divergence;     "Mean divergence from family consensus (%)"
    )
"""

HUB_TXT = """hub vgpRepeatConsensus
shortLabel VGP Repeat Consensus
longLabel Multi-tool repeat annotation consensus for VGP assemblies
useOneFile off
email {email}
descriptionUrl documentation.html
"""


def write_trackdb(ran_tools, path, palette=None, tools=None,
                  vocab_version: str = "") -> str:
    """Emit trackDb.txt.

    The UCSC contributed-tracks layout requires one trackDb that works for EVERY
    assembly directory, so nothing here may reference an assembly, and every
    file named must exist in every directory -- including empty placeholders for
    tools that did not run.
    """
    L = []
    A = L.append
    A("# Multi-tool repeat annotation consensus.")
    A(f"# Classification vocabulary: {vocab_version}")
    A("# Generated by vgptrack -- do not edit by hand.")
    A("")
    # ---- container
    A("track repeatConsensus")
    A("superTrack on show")
    A("shortLabel Repeat Consensus")
    A("longLabel Multi-tool repeat annotation consensus and per-tool detail")
    A("group varRep")
    A("html documentation")
    A("")
    # ---- summary
    A("    track repeatSummary")
    A("    parent repeatConsensus")
    A("    bigDataUrl repeatSummary.bb")
    A("    shortLabel Repeat Summary")
    A("    longLabel Repeat consensus: class, tool support and classification agreement")
    A("    type bigBed 12 +")
    A("    itemRgb on")
    A("    visibility pack")
    A("    searchIndex name")
    A("    maxItems 100000")
    A("    labelFields name")
    A("    defaultLabelFields name")
    A("    mouseOverField mouseOver")
    A("    priority 1")
    A("    html documentation")
    A("")
    # ---- signals
    for name, label, longlab, colour, vmax, prio in [
        ("repeatSupport", "Tool Support", "Number of distinct tools calling a repeat at each base",
         "60,60,160", "3", 2),
        ("repeatSupportFrac", "Support Fraction",
         "Supporting tools as a fraction of tools able to call this class",
         "60,120,60", "1", 3),
        ("repeatDivergence", "Divergence", "Mean divergence from family consensus (%)",
         "160,60,60", "40", 4),
    ]:
        A(f"    track {name}")
        A("    parent repeatConsensus")
        A(f"    bigDataUrl {name}.bw")
        A(f"    shortLabel {label}")
        A(f"    longLabel {longlab}")
        A("    type bigWig")
        A(f"    color {colour}")
        A(f"    viewLimits 0:{vmax}")
        A("    autoScale off")
        A("    maxHeightPixels 100:40:8")
        A("    visibility full")
        A(f"    priority {prio}")
        A("    html documentation")
        A("")
    # ---- discordance
    A("    track toolUnique")
    A("    parent repeatConsensus")
    A("    bigDataUrl toolUnique.bb")
    A("    shortLabel Single-tool Calls")
    A("    longLabel Intervals called by exactly one tool (discordance)")
    A("    type bigBed 9 +")
    A("    itemRgb on")
    A("    visibility dense")
    A("    searchIndex name")
    A("    priority 5")
    A("    html documentation")
    A("")
    # ---- per-tool composite
    A("    track repeatByTool")
    A("    parent repeatConsensus")
    A("    compositeTrack on")
    A("    shortLabel Repeats by Tool")
    A("    longLabel Per-tool repeat annotation, full detail")
    A("    type bigBed 9 +")
    A("    visibility hide")
    A("    priority 6")
    A("    html documentation")
    A("")
    for t in (tools if tools is not None else ran_tools):
        note = "" if getattr(t, "ran", True) else " [NOT RUN on this assembly]"
        A(f"        track repeat_{t.tool_id}")
        A("        parent repeatByTool")
        A(f"        bigDataUrl repeat_{t.tool_id}.bb")
        A(f"        shortLabel {t.short_label}{'' if getattr(t,'ran',True) else ' (n/a)'}")
        A(f"        longLabel {t.long_label}{note}")
        A("        type bigBed 9 +")
        A("        itemRgb on")
        A("        searchIndex name")
        A(f"        color {t.color}")
        A(f"        priority {t.priority}")
        A("        html documentation")
        A("")
    text = "\n".join(L)
    with open(path, "w") as fh:
        fh.write(text)
    return text


def pertool_columns() -> list:
    """Column order of the per-tool BED, so an empty placeholder can be written
    for a tool that did not run without constructing any rows.

    Parsed from the autoSql so the two can never drift. The pattern must match
    array types (`char[1] strand`) as well as scalars -- dropping `strand` here
    would shift every subsequent column by one.
    """
    import re as _re
    return _re.findall(r"^\s+\S+\s+(\w+)\s*(?:\[[^\]]*\])?\s*;",
                       PERTOOL_AS, flags=_re.M)


def write_hub_files(hub_root: str, assembly: str, twobit: str | None = None,
                    email: str = "", description: str = "") -> None:
    """Write hub.txt, genomes.txt, groups.txt and the hub-level description.

    genomes.txt is APPENDED to, not overwritten: a hub carries one block per
    assembly, and building a second assembly must not erase the first.
    """
    os.makedirs(hub_root, exist_ok=True)
    hub_txt = os.path.join(hub_root, "hub.txt")
    if not os.path.exists(hub_txt):
        with open(hub_txt, "w") as fh:
            fh.write(HUB_TXT.format(email=email or "CONTACT_EMAIL_HERE"))

    gpath = os.path.join(hub_root, "genomes.txt")
    existing = open(gpath).read() if os.path.exists(gpath) else ""
    if f"genome {assembly}" not in existing:
        block = [f"genome {assembly}", f"trackDb {assembly}/trackDb.txt",
                 "groups groups.txt"]
        if description:
            block.append(f"description {description}")
        if twobit:
            block.append(f"twoBitPath {twobit}")
        with open(gpath, "a") as fh:
            if existing and not existing.endswith("\n\n"):
                fh.write("\n")
            fh.write("\n".join(block) + "\n\n")

    gr = os.path.join(hub_root, "groups.txt")
    if not os.path.exists(gr):
        with open(gr, "w") as fh:
            fh.write("name varRep\nlabel Variation and Repeats\n"
                     "priority 1\ndefaultIsClosed 0\n")

    doc = os.path.join(hub_root, "documentation.html")
    if not os.path.exists(doc):
        with open(doc, "w") as fh:
            fh.write(HUB_DESC)


HUB_DESC = """<h2>VGP Multi-Tool Repeat Annotation</h2>
<p>Transparent, multi-tool repeat evidence for Vertebrate Genomes Project
assemblies. Each assembly directory carries a consensus summary track, per-base
support and divergence signals, a single-tool discordance track, and the full
unmodified output of every repeat annotation tool that was run.</p>
<p>These are <b>evidence</b> tracks, not an official annotation. Where tools
disagree, the disagreement is displayed rather than resolved.</p>
<p>See the per-track documentation within each assembly directory for display
conventions and methods.</p>
"""


def write_docs(outdir: str, assembly: str, cmap, tools) -> str:
    """Per-assembly track documentation page (UCSC requires one per track; a
    single shared page referenced by every stanza satisfies this)."""
    rows = "\n".join(
        f"<tr><td>{t.tool_id}</td><td>{t.short_label}</td>"
        f"<td>{t.version}</td><td>{t.scope}</td></tr>" for t in tools)
    html = f"""<h2>Description</h2>
<p>Repeat annotation for <b>{assembly}</b> from several independent tools, shown
both as a consensus summary and as unmodified per-tool detail. Nothing is
filtered on the basis of agreement: a call made by one tool alone is displayed
as prominently as one made by all.</p>

<h2>Tools</h2>
<table class="stdTbl"><tr><th>ID</th><th>Tool</th><th>Version</th>
<th>Detection scope</th></tr>
{rows}</table>
<p>A tool that did not run on this assembly still has a track, containing no
features. Absence of a feature in such a track is not evidence of absence of a
repeat.</p>

<h2>Repeat Summary</h2>
<p>One feature per repeat element, where an element is a maximal run of covered
bases whose consensus classification stays compatible. BED12 geometry carries
the boundary disagreement:</p>
<ul>
<li><b>Thick block</b> &mdash; the longest run where every tool <i>able</i> to
call this class did call it. An element drawn entirely thin has no such core.</li>
<li><b>Thin extent</b> &mdash; the union of all tool calls.</li>
<li><b>Colour</b> &mdash; consensus class at the level the tools agree on.
Black marks a class conflict.</li>
</ul>
<p>Hovering shows class, support out of the eligible denominator, agreement
depth, any conflict, core size and mean divergence.</p>

<h2>Support and agreement</h2>
<p>Support counts <b>distinct tools</b>. Two overlapping calls from one tool
count once. The denominator is the number of tools capable of detecting the
consensus class, so a structural LTR finder is not counted as dissenting at a
SINE.</p>
<p>Agreement is reported as a <b>depth</b> on the classification hierarchy, not
as a boolean, because tools classify at different resolutions. A tool saying
<code>DNA</code> where another says <code>DNA/hAT-Ac</code> is agreement at
class level, not disagreement.</p>

<h2>Signals</h2>
<p><b>Tool Support</b> and <b>Support Fraction</b> give the per-base support
count and its fraction of the eligible denominator at full resolution &mdash;
the summary track's display merge is not applied to them. <b>Divergence</b> is
the mean percent divergence from the matched family consensus over the tools
that report one.</p>

<h2>Single-tool calls</h2>
<p>Intervals where exactly one tool made a call. The mouseover names the other
tools that were capable of calling that class and did not, which is a stronger
statement than a tool that could never have seen it.</p>

<h2>Classification vocabulary</h2>
<p>Raw labels are preserved verbatim in the per-tool tracks. The harmonized
path shown in the summary comes from a curated map, version
<code>{cmap.version}</code>. This vocabulary is <b>provisional</b> and will be
revised when the unified Dfam/Repbase classification is published; the map is a
data file, not code, and re-running the pipeline against a new version rebuilds
every track.</p>

<h2>Caveats</h2>
<ul>
<li>Support is a measure of <i>agreement</i>, not of correctness. Tools sharing
a library or an algorithm are not independent evidence.</li>
<li>Divergence values come from different tools' own estimates and are not
strictly comparable between tools.</li>
<li>Boundary disagreement is common: fewer than 40% of calls have a start
within 10 bp of another tool's nearest start.</li>
</ul>
"""
    path = os.path.join(outdir, "documentation.html")
    with open(path, "w") as fh:
        fh.write(html)
    return html


OVERLAP_TEXT = {
    "none": "no overlap with other hits from this tool",
    "nested_inner": "nested inside a larger element from this tool",
    "nested_host": "contains a smaller nested element from this tool",
    "redundant": "redundant with another hit from this tool (library redundancy)",
    "selfconflict": "conflicts with an overlapping hit from this tool",
}


def build_pertool_bed(hits: pd.DataFrame, tool, palette) -> pd.DataFrame:
    """BED9+9 for one tool. Raw labels are shown verbatim next to the mapping."""
    h = hits[hits.tool_id == tool.tool_id]
    if h.empty:
        return pd.DataFrame(columns=range(18))
    cons = h.canonical_path.to_numpy()
    upath, uinv = np.unique(cons.astype(str), return_inverse=True)
    rgb = np.array([palette.color_for(p) for p in upath], dtype=object)[uinv]

    def fmt(col, suffix="%"):
        v = h[col].to_numpy()
        return np.where(pd.isna(v), "not reported",
                        np.char.add(np.round(v.astype(float), 1).astype(str), suffix))

    rs = h.repeat_start.to_numpy(); re_ = h.repeat_end.to_numpy()
    crange = np.where(pd.isna(rs) | pd.isna(re_), "not reported",
                      np.char.add(np.char.add(
                          pd.Series(rs).fillna(0).astype("Int64").astype(str).to_numpy(), "-"),
                          pd.Series(re_).fillna(0).astype("Int64").astype(str).to_numpy()))
    sc = h.score.to_numpy()
    sc = np.clip(pd.to_numeric(pd.Series(sc), errors="coerce").fillna(0).to_numpy(), 0, 1000)
    return pd.DataFrame({
        "chrom": h.chrom.to_numpy(),
        "chromStart": h.chromStart.to_numpy(),
        "chromEnd": h.chromEnd.to_numpy(),
        "name": h.name.to_numpy(),
        "score": sc.astype(int),
        "strand": np.where(h.strand.isin(["+", "-"]).to_numpy(), h.strand.to_numpy(), "."),
        "thickStart": h.chromStart.to_numpy(),
        "thickEnd": h.chromEnd.to_numpy(),
        "itemRgb": rgb,
        "rawClass": h.repeat_class_family.fillna("none").to_numpy(),
        "canonicalClass": cons,
        # The schema calls this "divergence from family consensus", which is
        # true for library-based tools only. A tool measuring something else
        # says so in the value, since one .as is shared by every per-tool track.
        "divergence": (fmt("perc_div") if tool.divergence_is_consensus
                       else np.char.add(
                           fmt("perc_div"),
                           " (unit-to-unit within array, NOT vs consensus)")),
        "deletion": fmt("perc_del") if "perc_del" in h else "not reported",
        "insertion": fmt("perc_ins") if "perc_ins" in h else "not reported",
        "consensusRange": crange,
        "evidence": h.evidence.astype(str).to_numpy(),
        "overlapStatus": [OVERLAP_TEXT.get(s, s) for s in h.self_rel.astype(str)],
        "hitId": h.hit_id.fillna(".").to_numpy(),
    })


def _deepest(path: str, palette) -> str:
    """Human-readable name for a canonical path: its most specific term.

    `repeat:TE:ClassII:TIR:CACTA` -> `CACTA`; a bare `repeat` has no informative
    tail, so it falls back to the palette's label for that path.
    """
    tail = str(path).rsplit(":", 1)[-1] if path else ""
    if not tail or tail in ("repeat", "TE", "ClassI", "ClassII", "nonTE"):
        return palette.label_for(path)
    return tail


def build_tool_unique_bed(segments: pd.DataFrame, tools, palette) -> pd.DataFrame:
    """Intervals called by exactly one tool -- the discordance track.

    This is the track that answers "what would I lose by trusting one tool?".
    ``otherEligible`` names the tools that COULD have called this class and did
    not, which is the actually informative comparison: a locus missed by two
    capable tools is a stronger outlier than one missed by tools that were never
    able to see it.

    Built from SEGMENTS, not display elements. An element carries the maximum
    support seen anywhere within it, so a 900 bp element with a 200 bp
    single-tool tail reports n_support=3 and its unique tail would vanish.
    Segment-level construction recovers the full 91.1 Mb rather than the 51.9 Mb
    that element-level filtering yields; adjacent single-tool segments from the
    same tool are then merged back so the track stays browsable.
    """
    e = segments[segments.n_support == 1]
    if e.empty:
        return pd.DataFrame()
    e = e.sort_values(["chrom", "chromStart"], kind="stable").reset_index(drop=True)
    # Merge adjacent single-tool runs that share tool AND consensus class.
    adj = np.zeros(len(e), dtype=bool)
    adj[1:] = ((e.chromStart.to_numpy()[1:] == e.chromEnd.to_numpy()[:-1]) &
               (e.chrom.to_numpy()[1:] == e.chrom.to_numpy()[:-1]))
    for col in ("mask", "consensus_id"):
        v = e[col].to_numpy()
        adj[1:] &= v[1:] == v[:-1]
    gid = np.cumsum(~adj) - 1
    lens = (e.chromEnd - e.chromStart).to_numpy()
    e2 = e.assign(_dw=np.where(np.isnan(e.mean_div.to_numpy()), 0.0,
                              e.mean_div.to_numpy() * lens),
                  _dn=np.where(np.isnan(e.mean_div.to_numpy()), 0, lens))
    g = e2.groupby(gid, sort=False)
    dsum = g._dw.sum().to_numpy(); dn = g._dn.sum().to_numpy()
    e = pd.DataFrame({
        "chrom": g.chrom.first().to_numpy(),
        "chromStart": g.chromStart.min().to_numpy(),
        "chromEnd": g.chromEnd.max().to_numpy(),
        "mask": g["mask"].first().to_numpy(),
        "eligible_mask": g.eligible_mask.first().to_numpy(),
        "consensus_path": g.consensus_path.first().to_numpy(),
        "mean_div": np.where(dn > 0, dsum / np.maximum(dn, 1), np.nan),
    })
    bits = {t.tool_id: t.bit for t in tools}
    m = e["mask"].to_numpy()
    em = e.eligible_mask.to_numpy()
    tool_of = np.full(len(e), "", dtype=object)
    rgb = np.full(len(e), "128,128,128", dtype=object)
    for t in tools:
        sel = (m >> t.bit & 1).astype(bool)
        tool_of[sel] = t.tool_id
        rgb[sel] = t.color
    others = []
    for i in range(len(e)):
        miss = [t.tool_id for t in tools
                if (em[i] >> bits[t.tool_id] & 1) and not (m[i] >> bits[t.tool_id] & 1)]
        others.append(",".join(miss) if miss else "none")
    cons = e.consensus_path.to_numpy()
    d = e.mean_div.to_numpy()
    return pd.DataFrame({
        "chrom": e.chrom.to_numpy(),
        "chromStart": e.chromStart.to_numpy(),
        "chromEnd": e.chromEnd.to_numpy(),
        # The palette label is deliberately coarse (<= 8 colours), so using it
        # as the feature NAME throws away resolution the tool actually provided:
        # a CACTA call would read "DNA". Name from the deepest term of the
        # canonical path, falling back to the palette label only when the path
        # carries nothing below `repeat`.
        "name": [f"{t} only: {_deepest(c, palette)}" for t, c in zip(tool_of, cons)],
        "score": 1000,
        "strand": ".",
        "thickStart": e.chromStart.to_numpy(),
        "thickEnd": e.chromEnd.to_numpy(),
        "itemRgb": rgb,
        "tool": tool_of,
        "canonicalClass": cons,
        "otherEligible": others,
        "divergence": np.where(np.isnan(d), "not reported",
                               np.char.add(np.round(d, 1).astype(str), "%")),
    })
